version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: bookstore
    ports: 
      - 8080:8080
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile
      target: mydb
      args:
        - MYSQL_ROOT_PASSWORD=root
    ports: 
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql