{
 "title": "bookstore-sample",
 "description": "Dashboard that graphs metrics exported via Prometheus plugin",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    { "expr": "sum(bookstore_requests_total)", "legendFormat": "Requests" },
    { "expr": "sum(bookstore_responses_total)", "legendFormat": "Success Responses" },
    {
     "expr": "sum(bookstore_failed_responses_total)",
     "legendFormat": "Failed Responses"
    }
   ]
  },
  { "title": "Application Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bookstore_requests_total{handler=~\".*/emp.*\"})",
     "legendFormat": "/emp"
    },
    {
     "expr": "sum(bookstore_requests_total{handler=~\".*/book.*\"})",
     "legendFormat": "/book"
    },
    {
     "expr": "sum(bookstore_requests_total{handler=~\".*/purchase.*\"})",
     "legendFormat": "/purchase"
    },
    {
     "expr": "sum(bookstore_requests_total{handler=~\".*/feedback.*\"})",
     "legendFormat": "/feedback"
    }
   ]
  },
  {
   "title": "Total",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "responses" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bookstore_responses_total{handler=~\".*/emp.*\", code=\"200\"})",
     "legendFormat": "/emp"
    },
    {
     "expr": "sum(bookstore_responses_total{handler=~\".*/book.*\", code=\"200\"})",
     "legendFormat": "/book"
    },
    {
     "expr": "sum(bookstore_responses_total{handler=~\".*/purchase.*\", code=\"200\"})",
     "legendFormat": "/purchase"
    },
    {
     "expr": "sum(bookstore_responses_total{handler=~\".*/feedback.*\", code=\"200\"})",
     "legendFormat": "/feedback"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(bookstore_requests_total{handler=~\".*/emp.*\"}[1m]))",
     "legendFormat": "/emp"
    },
    {
     "expr": "sum(rate(bookstore_requests_total{handler=~\".*/book.*\"}[1m]))",
     "legendFormat": "/book"
    },
    {
     "expr": "sum(rate(bookstore_requests_total{handler=~\".*/purchase.*\"}[1m]))",
     "legendFormat": "/purchase"
    },
    {
     "expr": "sum(rate(bookstore_requests_total{handler=~\".*/feedback.*\"}[1m]))",
     "legendFormat": "/feedback"
    }
   ]
  },
  {
   "title": "Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(bookstore_responses_total{handler=~\".*/emp.*\"}[1m]))",
     "legendFormat": "/emp"
    },
    {
     "expr": "sum(rate(bookstore_responses_total{handler=~\".*/book.*\"}[1m]))",
     "legendFormat": "/book"
    },
    {
     "expr": "sum(rate(bookstore_responses_total{handler=~\".*/purchase.*\"}[1m]))",
     "legendFormat": "/purchase"
    },
    {
     "expr": "sum(rate(bookstore_responses_total{handler=~\".*/feedback.*\"}[1m]))",
     "legendFormat": "/feedback"
    }
   ]
  },
  {
   "title": "Failed Responses",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(handler) (bookstore_failed_responses_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(handler) (bookstore_failed_responses_total{code!=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}