{
 "title": "bookstore",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(bookstore_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Success Responses",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(bookstore_responses_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Responses",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bookstore_failed_responses_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests of Each Handler",
   "type": "timeseries",
   "description": "Filtered with respect to handler",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(handler) (bookstore_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses of Each Handler",
   "type": "timeseries",
   "description": "Filtered with respect to handler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(handler) (bookstore_responses_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Responses of Each Handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(handler) (bookstore_failed_responses_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}